// Dependencies
import type { Metadata } from "next";

// Components
// import Header from "@/components/header";
// import Footer from "@/components/footer";

// Styles
import "@/styles/index.scss";
import DarkHeader from "@/components/darkHeader";
import DarkFooter from "@/components/darkFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        <DarkHeader />
        {children}
        {/* <Footer /> */}
        <DarkFooter />
      </body>
    </html>
  );
}
